### ISSUE TITLE
Bank doesn't do interest.

### ISSUE THREAD

**Issue by mmominecraft** [iConomy/Core#126]
I am encountering an issue with iConomy 5.0.1 and CraftBukkit 953. I'm not receiving any error messages for this issue but rather, a feature is simply not working. I have a bank named CentralBank setup on the server I run. All my players have accounts with the bank and money deposited in it. I have set up iConomy to generate 0.02% interest hourly, with the goal of a .48% interest rate daily. I want this to happen regardless of whether the player is online or not. I also want this to send a message to the player so they know what they earned.

Here is what my config.yml looks like for banks/interest:

Code:

```
Banking:
    Enabled: true
    Accounts:
        Multiple: true
Interest:
    Enabled: true
    Online: false                                  # Only give to players who are online?
    Announce:
        Enabled: true
    Interval:
        Seconds: 3600
    Amount:
        Cutoff: 50000.0                               # Amount limit to be met until we stop giving interest. (0.0 for no limit)
        On: 'Banks'                             # Banks or Players
        Percent: 0.02                              # Percent of holdings to give / take (Negative to take) (Overrides Min/Max)
        Maximum: 1                                # (Range) Maximum amount for random in between. (Make Max/Min equal for a flat-rate amount ie: 5/5)
        Minimum: 2                                # (Range) Minimum amount for random in between.
```

Yet no interest is being generated every 3600 secords (1 hour). The server has since been up for nearly 2 hours since the last restart, and no interest announcement has been generated. Is there any reason why this would be occurring? My character has a bank account of 950, which means it should have gained 19 in the last hour but no such event occurred. Any fixes/suggestions?
