### ISSUE TITLE
Problem with interersts on bank accounts

### ISSUE THREAD

**Issue by Ture** [iConomy/Core#128]
I switched from players to banks yesterday to encourage users to use the bank feature. Unfortunatly they still get interests for what they have in their pockets instead in their bank accounts.

---

```
Interest:
    Enabled: true
    Online: true                                  # Only give to players who are online?
    Announce:
        Enabled: true
    Interval:
        Seconds: 1200
    Amount:
        Cutoff: 1000000.0                               # Amount limit to be met until we stop giving interest. (0.0 for no limit)
        On: 'Banks'                               # Banks or Players
        Percent: 2.0                              # Percent of holdings to give / take (Negative to take) (Overrides Min/Max)
        Maximum: 2                                # (Range) Maximum amount for random in between. (Make Max/Min equal for a flat-rate amount ie: 5/5)
        Minimum: 2                                # (Range) Minimum amount for random in between.
```
