### ISSUE TITLE
Database error MySQL

### ISSUE THREAD

**Issue by Icedave** [iConomy/Core#151]
I installed iConomy6, done all the parts to set up MySQL. When i started my server it created connects to my database but if i go into my database into my table (i use the MySQL Workbench) it comes up with this error when i would look into the table.
Action :select \* from `iconomy6`.`iconomy6` LIMIT 0, 1000
Message: Error: `iconomy6`.`iconomy6`: table data is not editable because there is no primary key defined for the table
I Use the new 1185 built from bukkit and 1.8 minecraft. my config from iConomy looks like this
  Database:
    # Databases Supported:
    # Flatfile, FF, mini, minidb
    #  - These all equate to miniDB
    ##
    # item, items, inventory, inventoryDB
    #  - These all equate to InventoryDB, which uses inventory for storage
    ##
    # xp, exp, orb, xpdb, expdb, orbdb
    #  - These all equate to ExperienceDB, which relies on Experience for balance.
    ##
    # mysql, mysqldb
    #  - These will attempt to connect to MySQL
    ##
    # sqlite, sqlite2, sqlite3, sqlitedb
    #  - These will attempt to create & connect to SQLite
    ##
    # postgre, postgreSQL, postgreDB
    #  - These will attempt to connect to PostgreSQL
    Type: 'mysql'

```
# These are for InventoryDB only.
# MajorItem is the item or block ID of the major currency
# MinorItem is the item or block ID of the minor currency
# e.g. MajorItem: 266, MinorItem: 265 for Gold/Iron
MajorItem: 266
MinorItem: 265

# This controls the database name, by default it is iConomy
Table: 'iConomy6'

# URL is for SQL Databases Only
##
# Path to iConomy folder is easy, it's the COMPLETE path.
# (Mine) G:\MineCraft\plugins\iConomy\
# Won't be the same as yours, but it usually looks like that.
##
# [H2DB Default] h2:path/to/iConomy/folder/iConomy;AUTO_RECONNECT=TRUE
# [SQLite Default] sqlite:path/to/iConomy/folder/iConomy.db
##
# Binary Databases use ip:port style connections.
# ip
#  - is the connection identifier (internet protocol)
#  - for ipv6 usually encased in brackets [::1]
# port
#  - the port that the database is listening on
#  - defaults: 3306 for mysql, postgre is either 5740 or 5432
##
# [MySQL Default] mysql://localhost:3306/iConomy
# [Postgre Default] postgresql://localhost:5740/iConomy
URL: 'mysql://localhost:3306/iConomy6'

# Login details for binary databases
Username: 'root'
Password: 'xxxxxxxx'

# Conversion allows you to convert your old 5.x to the new 6.x
# All is currently unused.
# URL is for MySQL only, H2DB doesn't use it.
Conversion:
  # Set to True, After converting, change this back to false!
  Enabled: false

  # Database Type, H2DB or MySQL
  Type: 'MySQL'

  # Database Table
  Table: 'iConomy6'

  # Database URL without table at the end.
  URL: 'mysql://localhost:3306'

  # Username / Password
  # H2DB does not use this. MySQL Only.
  Username: 'root'
  Password: 'xxxxxxxx'

  # Unused ATM.
  All: true
```

could anyone help me out what the problem is??
thx
