### ISSUE TITLE
iConomy: Interest are not working!!!

### ISSUE THREAD

**Issue by nukeooverqc** [iConomy/Core#256]
Here is the part of config file.

  # Controls amount of money gained at a set interval.
  Interest:
    Enabled: true

```
# Only give interest to players who are currently online?
Online: true

Announce:
  # Send a message when the player gains interest?
  Enabled: false

Interval:
  #  Interval is done in seconds, here is a easy reference table for commonly set intervals:
  #   1 minute = 60 seconds
  #   1 hour = 1 minute * 60 = 3600 seconds
  #   1 day = 1 hour * 24 = 86400 seconds
  #   1 week = 1 day * 7 = 604800 seconds
  Seconds: 60

Amount:
  # The balance to be met where we stop giving interest.
  #0.0 for no limit
  Cutoff: 0.0

  # Percentage of holdings to give / take (Negative to take) (Overrides Min/Max)
  Percent: 5.0

  # This is range based, to set a "flat" or "constant" rate, set each (Maximum and Minimum) to the same number.
  # If the two numbers are different, it will be a random amount in-between the two.
  Maximum: 1
  Minimum: 2
```
