### ISSUE TITLE
Issue Regarding Interest Payouts.

### ISSUE THREAD

**Issue by Antdog319** [iConomy/Core#293]
[INFO] This server is running CraftBukkit version git-Bukkit-4c3da3f (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

[WARN] Exception in thread "Timer-1"
[WARN] java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
[WARN]  at com.iCo6.system.Interest.run(Interest.java:31)
[WARN]  at java.util.TimerThread.mainLoop(Unknown Source)
[WARN]  at java.util.TimerThread.run(Unknown Source)

Config regarding interest in case I did something wrong there:

  Interest:
    Enabled: true

```
# Only give interest to players who are currently online?
Online: true

Announce:
  # Send a message when the player gains interest?
  Enabled: true

Interval:
  #  Interval is done in seconds, here is a easy reference table for commonly set intervals:
  #   1 minute = 60 seconds
  #   1 hour = 1 minute * 60 = 3600 seconds
  #   1 day = 1 hour * 24 = 86400 seconds
  #   1 week = 1 day * 7 = 604800 seconds
  Seconds: 60

Amount:
  # The balance to be met where we stop giving interest.
  #0.0 for no limit
  Cutoff: 0.0

  # Percentage of holdings to give / take (Negative to take) (Overrides Min/Max)
  Percent: 0.0

  # This is range based, to set a "flat" or "constant" rate, set each (Maximum and Minimum) to the same number.
  # If the two numbers are different, it will be a random amount in-between the two.
  Maximum: 0.10
  Minimum: 0.01
```

  Database:
    # Databases Supported:
    # Flatfile, FF, mini, minidb
    #  - These all equate to miniDB
    ##
    # item, items, inventory, inventoryDB
    #  - These all equate to InventoryDB, which uses inventory for storage
    ##
    # xp, exp, orb, xpdb, expdb, orbdb
    #  - These all equate to ExperienceDB, which relies on Experience for balance.
    ##
    # mysql, mysqldb
    #  - These will attempt to connect to MySQL
    ##
    # sqlite, sqlite2, sqlite3, sqlitedb
    #  - These will attempt to create & connect to SQLite
    ##
    # postgre, postgreSQL, postgreDB
    #  - These will attempt to connect to PostgreSQL
    Type: 'minidb'

Greatly appreciate any follow up on this issue.
